FROM openjdk:23

# Install JavaFX
RUN apt-get update && \
    apt-get install -y openjfx

WORKDIR /app
COPY ./src/ .
EXPOSE 30001
RUN mkdir build && javac --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml -d build networking/Server.java
ENTRYPOINT ["java", "--module-path", "/usr/share/openjfx/lib", "--add-modules", "javafx.controls,javafx.fxml", "-cp", "build", "networking.Server"]