# Made by Sultan Amrani and Nova Driscoll
# GitHub Copilot (Gemini 2.0 Flash) used to assist in writing this Dockerfile

# Docker Image
FROM openjdk:23

# Copy source code
COPY ./src/ .
# Copy the JavaFX SDK (must manually copy dependencies in)
COPY ./lib ./lib/.
# Expose Server port
EXPOSE 30001

# Compile with JavaFX
RUN mkdir build && javac --module-path ./lib --add-modules javafx.controls,javafx.fxml -d build networking/Server.java

# Run with JavaFX
ENTRYPOINT ["java", "--module-path", "./lib", "--add-modules", "javafx.controls,javafx.fxml", "-cp", "build", "networking.Server"]